version: '3'
services:
  my-app:
    image: jbecera/articles-products-and-express-routes:${IMAGE_VERSION}-local
    command: ["./node_modules/.bin/nodemon", "app.js"] 
    # ['npm', 'run', 'dev']
    container_name: art-prod-express
    volumes:
      - ".:/app/:rw"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "${PORT}:${PORT}"
      # - '3000:3000'
      # - '3001:3001'
    networks:
      - my-app-network

networks:
  my-app-network: